sudo: required

services:
        - docker

before_install:
        - docker pull outcoldman/splunk:latest
        - docker run --hostname splunk -p 8000:8000 -d outcoldman/splunk
        - docker ps -a
        - npm install -g npm@latest

language: node_js

script:
        node sdkdo tests utils
