sudo: required

services:
        - docker

before_install:
        - echo $HOME
        - touch $HOME/.splunkrc
        - echo host=localhost >> $HOME/.splunkrc
        - echo username=admin >> $HOME/.splunkrc
        - echo password=changeme >> $HOME/.splunkrc
        - pwd
        - docker pull adamryman/splunk-travis-ci:latest
        - docker images
        - docker run -p 8089:8089 -d adamryman/splunk-travis-ci
        - docker ps -a
        - docker ps -q
        - sudo apt-get update
        - sudo apt-get install curl
        - curl --version
        - curl -k --verbose --sslv3 https://0.0.0.0:8089/services/auth/login -d username=admin -d password=changeme
        - curl -k --verbose https://localhost:8089/services/auth/login -d username=admin -d password=changeme
        - curl -k --verbose https://localhost:8089/services/auth/login -d username=admin -d password=changeme
        - export SPLUNK_HOME="/opt/splunk"

language: node_js

script:
        node sdkdo tests
