sudo: required

services:
        - docker

before_install:
        - docker pull adamryman/splunk-test:latest
        - docker run --hostname splunk -p 8000:8000 -d outcoldman/splunk
        - docker ps -a


language: node_js

script:
        node sdkdo tests context
