sudo: required

services:
        - docker

before_install:
        - docker pull adamryman/splunk-travis-ci:latest
        - docker run --hostname splunk -p 8089:8089 -d adamryman/splunk-travis-ci
        - docker ps -a
        - sudo apt-get update
        - sudo apt-get install curl
        - curl --version
        - curl -k --verbose --sslv3 https://0.0.0.0:8089/services/auth/login -d username=admin -d password=changeme
        - node sdkdo tests context
        - curl -k --verbose https://localhost:8089/services/auth/login -d username=admin -d password=changeme


language: node_js

script:
        node sdkdo tests context
