sudo: required

services:
        - docker

before_install:
        - echo host=localhost >> $HOME/.splunkrc
        - echo username=admin >> $HOME/.splunkrc
        - echo password=changeme >> $HOME/.splunkrc
        - export SPLUNK_HOME="/opt/splunk"
        - docker pull adamryman/splunk-travis-ci:latest
        - docker run -p 8089:8089 -d adamryman/splunk-travis-ci

language: node_js

script:
        node sdkdo tests
