sudo: required

services:
        - docker

before_install:
        - docker pull adamryman/splunk-test:latest
        - docker run --hostname splunk -p 8089:8089 -d adamryman/splunk-test
        - docker ps -a
        - curl -k https://localhost:8089/services/auth/login -d username=admin -d password=changeme
        - node sdkdo tests context
        - curl -k https://localhost:8089/services/auth/login -d username=admin -d password=changeme


language: node_js


script:
        node sdkdo tests context
